# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\"U\n\rInsertRequest\x12\x13\n\x0bnode_origin\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x13\n\x0b\x63lient_port\x18\x04 \x01(\x03\">\n\x0bInsertReply\x12\x13\n\x0bnode_insert\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"F\n\rLookupRequest\x12\x13\n\x0bnode_origin\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x13\n\x0b\x63lient_port\x18\x03 \x01(\x03\":\n\x0bLookupReply\x12\x0f\n\x07node_id\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2N\n\x04Node\x12\"\n\x06Insert\x12\x0e.InsertRequest\x1a\x06.Empty\"\x00\x12\"\n\x06Lookup\x12\x0e.LookupRequest\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTREQUEST']._serialized_start=14
  _globals['_INSERTREQUEST']._serialized_end=99
  _globals['_INSERTREPLY']._serialized_start=101
  _globals['_INSERTREPLY']._serialized_end=163
  _globals['_LOOKUPREQUEST']._serialized_start=165
  _globals['_LOOKUPREQUEST']._serialized_end=235
  _globals['_LOOKUPREPLY']._serialized_start=237
  _globals['_LOOKUPREPLY']._serialized_end=295
  _globals['_EMPTY']._serialized_start=297
  _globals['_EMPTY']._serialized_end=304
  _globals['_NODE']._serialized_start=306
  _globals['_NODE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
